### ISSUE TITLE
charades_map/charades_nanmap

### ISSUE THREAD

**Issue by pzhren** [gsig/charades-algorithms#17]
https://github.com/wykang/Charades/blob/adc58b7cfe2567f17cc7b62caf4ff4a13a1e8f22/utils/map.py#L26
m_ap = np.mean(m_aps)
m_ap = np.nanmean(m_aps)
Are these two evaluation indicators the same?

**Comment by gsig** [comment]
Yes. The second one was used in case there are ever any classes missing from the evaluation (when using custom evaluation sets etc), in which case the AP for the class would be 'nan', and the second one will ignore this.

Hope that helps,
Gunnar
