### ISSUE TITLE
Unusual Training Behaviour

### ISSUE THREAD

**Issue by ahmed-nad** [gsig/charades-algorithms#3]
I followed the instructions and proceeded towards retraining the rgbnet with default parameters, and ran it for 6 epochs with other parameters unchanged, I checked the epoch#.txt files and found out that the the network is predicting the same values for each video, the values change between epochs but stay the same for each video inside the file. 

As a debug step i also predicted some images using RESNET  inside and it was also giving same probabilities for any picture i feed in it, I tried every architecture

Ihave attached screenshot of one epoch file and .txt files for all epochs

![screen shot 2017-07-21 at 1 14 21 pm](https://user-images.githubusercontent.com/24569196/28454969-90f7ef6a-6e16-11e7-917a-ab565973c40b.png)
[Uploading epoch1.txt…]()
[Uploading epoch2.txt…]()
[Uploading epoch3.txt…]()
[Uploading epoch4.txt…]()
[Uploading epoch5.txt…]()

**Comment by gsig** [comment]
Strange. Is is definitely loading in the pretrained imagenet network? Is it finding all the data?

Can you attach your full log file? (At least up to the first few epochs)

**Comment by ahmed-nad** [comment]
I solved the issue, i think it was a problem with caffe loader module which i compiled myself, it was linking to an old version of protobuf thus causing problems, i reinstalled everything and the problem disappeared
