### ISSUE TITLE
Flow Conversion

### ISSUE THREAD

**Issue by ahmed-nad** [gsig/charades-algorithms#4]
How can i convert the 2 dimensional (u,v) obtained from dense optical flow algorithm to the id-0000.x and id-0000.y files, help appreciated.
How is the sequence numbered like the optical flow between images 1 and 2 is labelled 1.x and 1.y ?

**Comment by gsig** [comment]
Details about the flow and extracted frames can be found in the Charades README file [http://allenai.org/plato/charades/README.txt](http://allenai.org/plato/charades/README.txt)

Extracted flow and rgb frames are also provided at [http://allenai.org/plato/charades/](http://allenai.org/plato/charades/)
