### ISSUE TITLE
A question about charades action location label 

### ISSUE THREAD

**Issue by zhangxgu** [gsig/charades-algorithms#5]
As I run the dataset, I find that some videos' annotations about end time of action is bigger than the total length of that video. For example,\

name         action label                                                                total length
42K3H      c006 0.00 3.60;c008 0.00 5.00;c112 0.00 3.90                 3.5

\
This c008's end time is 5s > 3.5s. 
Should I just turn this 5 into 3.5 ?

**Comment by gsig** [comment]
Yes exactly. Just clip the labels into the defined interval. That's what we did in the Torch codebase.

Best,
Gunnar
