### ISSUE TITLE
Corrupted Pytorch model?

### ISSUE THREAD

**Issue by grantlj** [gsig/charades-algorithms#6]
hI,
The Pytorch model on dropbox: https://www.dropbox.com/s/p457h2ifi6v1qdz/twostream_rgb.pth.tar?dl=1, seems being corrupted:
I have tried to unzip the file on ubuntu with: tar xvf twostream_rgb.pth.tar:

tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

Could you help to fix this problem?

**Comment by gsig** [comment]
The .pth.tar was actually generated by pytorch directly. Does torch.load('filename.pth.tar') work?

**Comment by grantlj** [comment]
Yes, it works. Thank you for your assistance.
